# Generated by Django 4.0.4 on 2022-04-26 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asilar',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('asiAdi', models.CharField(max_length=25)),
                ('muayeneId', models.CharField(max_length=25)),
                ('ilacId', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Hayvan',
            fields=[
                ('küpeNo', models.AutoField(primary_key=True, serialize=False)),
                ('aile', models.CharField(max_length=25)),
                ('cins', models.CharField(max_length=25)),
                ('hsId', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='HayvanSahibi',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ad', models.CharField(max_length=255)),
                ('soyad', models.CharField(max_length=255)),
                ('telefon', models.CharField(max_length=11)),
                ('email', models.EmailField(max_length=254)),
                ('il', models.CharField(max_length=255)),
                ('ilce', models.CharField(max_length=255)),
                ('adres', models.CharField(max_length=255)),
                ('kullaniciId', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Ilaclar',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ad', models.CharField(max_length=255)),
                ('prospektus', models.CharField(max_length=50)),
                ('stokMiktari', models.CharField(max_length=25)),
                ('fiyat', models.DecimalField(decimal_places=2, max_digits=10, max_length=25)),
                ('asiMi', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ilceler',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('ilceAdi', models.CharField(max_length=255)),
                ('ilId', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Iller',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('ilAdi', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Kullanici',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tcNo', models.CharField(max_length=255)),
                ('parola', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Kurum',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('kurumAdi', models.CharField(max_length=25)),
                ('il', models.CharField(max_length=255)),
                ('ilce', models.CharField(max_length=25)),
                ('adres', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Muayeneler',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tarih', models.DateTimeField(auto_now_add=True)),
                ('sikayet', models.CharField(max_length=500)),
                ('kupeNo', models.CharField(max_length=255)),
                ('vetId', models.CharField(max_length=255)),
                ('poliklinikId', models.CharField(max_length=255)),
                ('randevuId', models.CharField(max_length=25)),
                ('muayeneYapildiMi', models.BooleanField(default=True)),
                ('receteNo', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Poliklinik',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('poliklinikAdi', models.CharField(max_length=25)),
                ('kurumId', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Randevular',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tarih', models.DateTimeField(auto_now_add=True)),
                ('geldiMi', models.BooleanField(default=True)),
                ('kupeNo', models.CharField(max_length=255)),
                ('vetId', models.CharField(max_length=255)),
                ('poliklinikId', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Recete',
            fields=[
                ('receteNo', models.AutoField(primary_key=True, serialize=False)),
                ('muayeneId', models.CharField(max_length=25)),
                ('ilacId', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='VeterinerHekim',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ad', models.CharField(max_length=25)),
                ('soyad', models.CharField(max_length=255)),
                ('sicilNo', models.CharField(max_length=11)),
                ('telefon', models.CharField(max_length=11)),
                ('email', models.EmailField(max_length=255)),
                ('poliklinikId', models.CharField(max_length=255)),
                ('kullaniciId', models.CharField(max_length=255)),
            ],
        ),
    ]
