# Generated by Django 4.0.3 on 2022-04-26 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Asilar',
        ),
        migrations.RenameField(
            model_name='muayeneler',
            old_name='kupeNo',
            new_name='küpeNo',
        ),
        migrations.RenameField(
            model_name='randevular',
            old_name='kupeNo',
            new_name='küpeNo',
        ),
        migrations.RemoveField(
            model_name='muayeneler',
            name='receteNo',
        ),
    ]
